version: '3.1'
services:
  korsa:
    image: mariadb:10.4.8
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=korsa
      - MYSQL_USER=korsa
      - MYSQL_PASSWORD=korsa
    ports:
      - '3310:3306'
