ALTER TABLE korsa.city MODIFY name VARCHAR(255) CHARACTER SET utf8;

INSERT INTO region (name, iso)
VALUES ('Tanger-Tétouan-Al Hoceïma', 'MA-01'),
       ('l''Oriental', 'MA-02'),
       ('Fès-Meknès', 'MA-03'),
       ('Rabat-Salé-Kénitra', 'MA-04'),
       ('Béni Mellal-Khénifra', 'MA-05'),
       ('Casablanca-Settat', 'MA-06'),
       ('Marrakech-Safi', 'MA-07'),
       ('Drâa-Tafilalet', 'MA-08'),
       ('Souss-Massa', 'MA-09'),
       ('Guelmim-Oued Noun', 'MA-10'),
       ('Laâyoune-Sakia El Hamra', 'MA-11'),
       ('Dakhla-Oued Ed-Dahab', 'MA-12');

INSERT INTO city (iso, name, region_iso) values
('MA-AGD', 'Agadir-Ida-Ou-Tanane', 'MA-09'),
('MA-HAO', 'Al Haouz', 'MA-07'),
('MA-HOC', 'Al Hoceïma', 'MA-01'),
('MA-AOU', 'Aousserd (EH)', 'MA-12'),
('MA-ASZ', 'Assa-Zag (EH-partial)', 'MA-10'),
('MA-AZI', 'Azilal', 'MA-05'),
('MA-BES', 'Benslimane', 'MA-06'),
('MA-BER', 'Berkane', 'MA-02'),
('MA-BRR', 'Berrechid', 'MA-06'),
('MA-BOD', 'Boujdour (EH)', 'MA-11'),
('MA-BOM', 'Boulemane', 'MA-03'),
('MA-BEM', 'Béni Mellal', 'MA-05'),
('MA-CAS', 'Casablanca', 'MA-06'),
('MA-CHE', 'Chefchaouen', 'MA-01'),
('MA-CHI', 'Chichaoua', 'MA-07'),
('MA-CHT', 'Chtouka-Ait Baha', 'MA-06'),
('MA-DRI', 'Driouch', 'MA-02'),
('MA-HAJ', 'El Hajeb', 'MA-03'),
('MA-JDI', 'El Jadida', 'MA-06'),
('MA-KES', 'El Kelâa des Sraghna', 'MA-07'),
('MA-ERR', 'Errachidia', 'MA-08'),
('MA-ESM', 'Es-Semara (EH-partial)', 'MA-11'),
('MA-ESI', 'Essaouira', 'MA-07'),
('MA-FAH', 'Fahs-Anjra', 'MA-01'),
('MA-FIG', 'Figuig', 'MA-02'),
('MA-FQH', 'Fquih Ben Salah', 'MA-05'),
('MA-FES', 'Fès', 'MA-03'),
('MA-GUE', 'Guelmim', 'MA-10'),
('MA-GUF', 'Guercif', 'MA-02'),
('MA-IFR', 'Ifrane', 'MA-03'),
('MA-INE', 'Inezgane-Ait Melloul', 'MA-09'),
('MA-JRA', 'Jerada', 'MA-02'),
('MA-KHO', 'Khouribga', 'MA-05'),
('MA-KHE', 'Khémisset', 'MA-04'),
('MA-KHN', 'Khénifra', 'MA-05'),
('MA-KEN', 'Kénitra', 'MA-04'),
('MA-LAR', 'Larache', 'MA-01'),
('MA-LAA', 'Laâyoune (EH)', 'MA-11'),
('MA-MAR', 'Marrakech', 'MA-07'),
('MA-MEK', 'Meknès', 'MA-03'),
('MA-MID', 'Midelt', 'MA-08'),
('MA-MOH', 'Mohammadia', 'MA-06'),
('MA-MOU', 'Moulay Yacoub', 'MA-03'),
('MA-MED', 'Médiouna', 'MA-06'),
('MA-MDF', 'M’diq-Fnideq', 'MA-01'),
('MA-NAD', 'Nador', 'MA-02'),
('MA-NOU', 'Nouaceur', 'MA-04'),
('MA-OUA', 'Ouarzazate', 'MA-08'),
('MA-OUD', 'Oued Ed-Dahab (EH)', 'MA-12'),
('MA-OUZ', 'Ouezzane', 'MA-01'),
('MA-OUJ', 'Oujda-Angad', 'MA-02'),
('MA-RAB', 'Rabat', 'MA-04'),
('MA-REH', 'Rehamna', 'MA-07'),
('MA-SAF', 'Safi', 'MA-07'),
('MA-SAL', 'Salé', 'MA-04'),
('MA-SEF', 'Sefrou', 'MA-03'),
('MA-SET', 'Settat', 'MA-06'),
('MA-SIB', 'Sidi Bennour', 'MA-06'),
('MA-SIF', 'Sidi Ifni', 'MA-10'),
('MA-SIK', 'Sidi Kacem', 'MA-04'),
('MA-SIL', 'Sidi Slimane', 'MA-04'),
('MA-SKH', 'Skhirate-Témara', 'MA-04'),
('MA-TNT', 'Tan-Tan (EH-partial)', 'MA-10'),
('MA-TNG', 'Tanger-Assilah', 'MA-01'),
('MA-TAO', 'Taounate', 'MA-03'),
('MA-TAI', 'Taourirt', 'MA-02'),
('MA-TAF', 'Tarfaya (EH-partial)', 'MA-11'),
('MA-TAR', 'Taroudannt', 'MA-09'),
('MA-TAT', 'Tata', 'MA-09'),
('MA-TAZ', 'Taza', 'MA-03'),
('MA-TIN', 'Tinghir', 'MA-08'),
('MA-TIZ', 'Tiznit', 'MA-09'),
('MA-TET', 'Tétouan', 'MA-01'),
('MA-YUS', 'Youssoufia', 'MA-07'),
('MA-ZAG', 'Zagora', 'MA-08');